Add uri as a required argument to CLI
nathf/puppeteer-healthcheck pull request #8
Opened 2018-03-07 05:53 UTC by petermekhaeil

2018-03-07 06:38 UTC, nathf commented
Thanks for the PR!

Some context around why it isn't currently demanded; I recently removed this demand because it conflicts with config usage. 

I think we need something like `check` https://github.com/yargs/yargs/blob/master/docs/api.md#checkfn-globaltrue to ensure Uri or config is passed otherwise throw an error. The help text could be updated to reflect that also

2018-03-07 06:50 UTC, petermekhaeil commented
Oops, missed that in the config in the README.md. 

`check` can do. Alternatively, we can check inside `run()` if `opts.uri` is a valid URL.

2018-03-07 07:17 UTC, nathf commented
Will puppeteer handle that for us? Fixtures are pretty immature at the moment, definitely should include that kind of scenario

2018-03-07 12:47 UTC, petermekhaeil commented
I've gone with this approach:

1. Clean requested url `opts.uri` by adding a default protocol of `http` (I am yet to test a http->https redirections get logged)
2. Validate that `opts.uri` is defined and the cleaned up URI is considered a valid URI.

Does this work?

2018-03-08 01:40 UTC, nathf requested changes
Couple of minor things

2018-03-08 01:40 UTC, nathf commented on src/assetChecks.js
> +    url = 'http://' + url;
I think it would be better if the default was `https`. Since most sites are moving away from plain http

2018-03-08 01:40 UTC, nathf commented on src/main.js
> +    const uri = cleanUrl(opts.uri);
We should move the sleep call inside the promise too, this check should come before we sleep.

2018-03-08 01:46 UTC, petermekhaeil commented on src/assetChecks.js
> +    url = 'http://' + url;
It might interest the user to see any redirections from http->https in the logs. 
Also, if one was to test an internal alias that isn't HTTPS yet.

Your thoughts?

2018-03-08 02:06 UTC, nathf commented on src/assetChecks.js
> +    url = 'http://' + url;
This is more of a sane default scenario (in my mind), if users wanted to check the redirect i feel they should be explicit about that.

I'll add this scenario to a list of fixtures that need to be added

2018-03-08 07:00 UTC, nathf approved these changes

2018-03-08 07:53 UTC, merged